<a href="https://colab.research.google.com/github/Tanishqqq19/modelling_simulations/blob/main/Week_4/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
scalar = torch.tensor(7)
scalar.item()

7

In [ ]:
vector = torch.tensor([[[7,7,4],
                       [6,6,4],
                       [5,5,4]]])

In [ ]:
vector.ndim

3

In [ ]:
vector.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor= torch.rand([224,224,3])
random_tensor

tensor([[[0.1578, 0.9123, 0.6073],
         [0.4198, 0.6974, 0.3988],
         [0.9677, 0.0105, 0.5918],
         ...,
         [0.6148, 0.7978, 0.8648],
         [0.0769, 0.8292, 0.0150],
         [0.3558, 0.7313, 0.5124]],

        [[0.4690, 0.8692, 0.0148],
         [0.7745, 0.0097, 0.5705],
         [0.4382, 0.6590, 0.2863],
         ...,
         [0.1741, 0.0738, 0.2993],
         [0.7611, 0.3381, 0.9767],
         [0.7465, 0.0222, 0.3745]],

        [[0.7886, 0.9299, 0.5913],
         [0.8364, 0.6287, 0.3518],
         [0.8090, 0.2166, 0.2397],
         ...,
         [0.8689, 0.1512, 0.9417],
         [0.5742, 0.6432, 0.9610],
         [0.6596, 0.0085, 0.3674]],

        ...,

        [[0.0245, 0.9461, 0.2321],
         [0.1229, 0.3141, 0.5462],
         [0.4002, 0.9590, 0.2433],
         ...,
         [0.6419, 0.4914, 0.2758],
         [0.7409, 0.0811, 0.6659],
         [0.6910, 0.3775, 0.3599]],

        [[0.3421, 0.9370, 0.2073],
         [0.6946, 0.9824, 0.2509],
         [0.

In [ ]:
###The dimensions of the above is 2 dimensions. Look at the number of square brackets

In [ ]:
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.range(1,10)

/tmp/ipython-input-1136815087.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten= torch.arange(start=0, end=1000, step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
ten_zeroes= torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=None, # defines the datatype of the tensor
                              device=None) # what device is your tensor on
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
torch.matmul(torch.rand(10,10), torch.rand(10,10))

torch.Size([10, 10])

In [4]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))